### ISSUE TITLE
Feature Request: Add system_code as option per switch

### ISSUE THREAD

**Issue by SvenKlimek** [tefinger/hass-brematic#1]
Issue: I have more than a four of these switches. So i have different system_codes for each set of 4 switches. This allows me to access the switches with the remotes.
Now i want to integrate all switches to home assisant but i can only set the system_code globally instead per switch.
An easy solution would be to allow system_code as option per entity in the config.

btw: Thank you for your effort on this integration!

**Comment by tefinger** [comment]
Hi @SvenKlimek sorry for the delayed response. 
I will have a look into this and try to add it. 
It was never a problem for me because my HA config is splitted into multiple files so for every switch/outlet I have a configuration file which look like this:

**living_room_floor_lamp.yml**
```
---
platform: brematic
host: !secret brematic_gateway_host
system_code: !secret brematic_gateway_system_code
switches:
  living_room_floor_lamp:
    unit_code: '00100'
    friendly_name: 'Stehlampe'
```

**dining_room_ball_lamp.yml**
```
---
platform: brematic
host: !secret brematic_gateway_host
system_code: !secret brematic_gateway_system_code
switches:
  dining_room_ball_lamp:
    unit_code: '01000'
    friendly_name: 'Kugellampe'
```

With this setup I have the option to use different system_codes for my outlets/switches.

**Comment by tefinger** [comment]
Will close this because you can achieve the desired result by using a config like this:

```yaml
switch:
    - platform: brematic
      host: '10.0.3.2'
      system_code: '01010'
      gateway_type: 'Brennenstuhl'
      switches:
        power_outlet:
          unit_code: '00010'
          friendly_name: Power Outlet
    - platform: brematic
      host: '10.0.3.2'
      system_code: '11110'
      gateway_type: 'Brennenstuhl'
      switches:
        power_outlet_2:
          unit_code: '10010'
          friendly_name: Power Outlet 2
```
