### ISSUE TITLE
[FEATURE] Add optional state template to determine power state of a switch

### ISSUE THREAD

**Issue by shawly** [tefinger/hass-brematic#9]
**Is your feature request related to a problem? Please describe.**
I'm using an old smartphone for my 3D printer as camera. When having it constantly plugged in to the charger it sometimes runs out of battery completely. To fix that I'm using a 433 MHz plug to turn off the charger if the phone reaches over 99% charge and turn it back on when the battery goes below 20%.
But sometimes my gateway sends the signal but my plug doesn't seem to receive it, so home assistant reports that the plug is turned off, but in reality it is still turned on and the phone slowly discharges until it completely runs out.

**Describe the solution you'd like**
To fix this issue it would be great to be able to add a template to a switch, like on the template switch in HA, where I can check for another entitys state.
Pretty much like this for example:
```yml
- platform: brematic
  host: "192.168.100.253"
  system_code: "10100"
  gateway_type: "ConnAir"
  switches:
    3d_printer_camera:
      unit_code: "10000"
      unit_type: "AB440SA"
      friendly_name: "3D Printer Camera Power"
      value_template: "{{ is_state('binary_sensor.phone_is_charging', 'on') }}"
```

This would basically turn the plug into a smart plug as long as the device that is plugged in can report its state to HA.
One could even connect an ESP8266 for example to the plug to determine if the plug is actually turned on or off, which is nice for devices that can't directly integrate into HA.

**Describe alternatives you've considered**
Well for now I've changed my automation to send the turn_on/turn_off command to the switch every 16 minutes (because the HA mobile app reports every 15 minutes) until the battery charging sensor reaches the state that is desired.
While this works it's just a workaround and I'm pretty sure that there are more use cases than the one I described for this feature which makes it desirable.

**Additional context**
